<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadet extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cadet_model');
    } 

    /*
     * Listing of cadet
     */
    function index()
    {
        $data['cadet'] = $this->Cadet_model->get_all_cadet();
        
        $data['_view'] = 'cadet/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cadet
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'admin' => $this->input->post('admin'),
				'password' => $this->input->post('password'),
				'firstName' => $this->input->post('firstName'),
				'rank' => $this->input->post('rank'),
				'primaryEmail' => $this->input->post('primaryEmail'),
				'secondaryEmail' => $this->input->post('secondaryEmail'),
				'primaryPhone' => $this->input->post('primaryPhone'),
				'secondaryPhone' => $this->input->post('secondaryPhone'),
				'flight' => $this->input->post('flight'),
				'position' => $this->input->post('position'),
				'groupMe' => $this->input->post('groupMe'),
				'middleName' => $this->input->post('middleName'),
				'lastName' => $this->input->post('lastName'),
				'rfid' => $this->input->post('rfid'),
				'major' => $this->input->post('major'),
				'bio' => $this->input->post('bio'),
				'AFGoals' => $this->input->post('AFGoals'),
				'awards' => $this->input->post('awards'),
				'PGoals' => $this->input->post('PGoals'),
            );
            
            $cadet_id = $this->Cadet_model->add_cadet($params);
            redirect('cadet/index');
        }
        else
        {            
            $data['_view'] = 'cadet/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cadet
     */
    function edit($rin)
    {   
        // check if the cadet exists before trying to edit it
        $data['cadet'] = $this->Cadet_model->get_cadet($rin);
        
        if(isset($data['cadet']['rin']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'admin' => $this->input->post('admin'),
					'password' => $this->input->post('password'),
					'firstName' => $this->input->post('firstName'),
					'rank' => $this->input->post('rank'),
					'primaryEmail' => $this->input->post('primaryEmail'),
					'secondaryEmail' => $this->input->post('secondaryEmail'),
					'primaryPhone' => $this->input->post('primaryPhone'),
					'secondaryPhone' => $this->input->post('secondaryPhone'),
					'flight' => $this->input->post('flight'),
					'position' => $this->input->post('position'),
					'groupMe' => $this->input->post('groupMe'),
					'middleName' => $this->input->post('middleName'),
					'lastName' => $this->input->post('lastName'),
					'rfid' => $this->input->post('rfid'),
					'major' => $this->input->post('major'),
					'bio' => $this->input->post('bio'),
					'AFGoals' => $this->input->post('AFGoals'),
					'awards' => $this->input->post('awards'),
					'PGoals' => $this->input->post('PGoals'),
                );

                $this->Cadet_model->update_cadet($rin,$params);            
                redirect('cadet/index');
            }
            else
            {
                $data['_view'] = 'cadet/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cadet you are trying to edit does not exist.');
    } 

    /*
     * Deleting cadet
     */
    function remove($rin)
    {
        $cadet = $this->Cadet_model->get_cadet($rin);

        // check if the cadet exists before trying to delete it
        if(isset($cadet['rin']))
        {
            $this->Cadet_model->delete_cadet($rin);
            redirect('cadet/index');
        }
        else
            show_error('The cadet you are trying to delete does not exist.');
    }
    
    /*
     * Makes sure cadet is authroized to login.
     */
    function login()
    {
        $cadet = $this->Cadet_model->get_cadet($this->input->post('rin'));
        
        $this->load->helper('form');
        $this->load->library('form_validation');

        $data['title'] = 'Login Page';

        if($this->input->post('psw') !== null && password_verify($this->input->post('psw'), $cadet['password']))
        {
            $this->load->library('session');
            $this->load->model('cadetevent_model');
            $this->load->model('announcement_model');

            // Sets session variable and loads closest 5 events
            $this->session->set_userdata('login', true);
            $data['events'] =  $this->cadetevent_model->get_last_five_events();
            $data['announcements'] =  $this->announcement_model->get_last_five_announcements();
            
            $this->load->view('templates/header', $data);
            $this->load->view('pages/home.php');
            $this->load->view('templates/footer');            
        }
        else
        {
            $this->load->view('templates/header', $data);
            $this->load->view('pages/login.php');
            $this->load->view('templates/footer');
        }
        
    }
    
}
