<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadetevent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cadetevent_model');
    } 

    /*
     * Listing of cadetevent
     */
    function index()
    {
        $data['cadetevent'] = $this->Cadetevent_model->get_all_cadetevent();
        
        $data['_view'] = 'cadetevent/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cadetevent
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'date' => $this->input->post('date'),
				'pt' => $this->input->post('pt'),
				'llab' => $this->input->post('llab'),
            );
            
            $cadetevent_id = $this->Cadetevent_model->add_cadetevent($params);
            redirect('cadetevent/index');
        }
        else
        {            
            $data['_view'] = 'cadetevent/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cadetevent
     */
    function edit($eventID)
    {   
        // check if the cadetevent exists before trying to edit it
        $data['cadetevent'] = $this->Cadetevent_model->get_cadetevent($eventID);
        
        if(isset($data['cadetevent']['eventID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'date' => $this->input->post('date'),
					'pt' => $this->input->post('pt'),
					'llab' => $this->input->post('llab'),
                );

                $this->Cadetevent_model->update_cadetevent($eventID,$params);            
                redirect('cadetevent/index');
            }
            else
            {
                $data['_view'] = 'cadetevent/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cadetevent you are trying to edit does not exist.');
    } 

    /*
     * Deleting cadetevent
     */
    function remove($eventID)
    {
        $cadetevent = $this->Cadetevent_model->get_cadetevent($eventID);

        // check if the cadetevent exists before trying to delete it
        if(isset($cadetevent['eventID']))
        {
            $this->Cadetevent_model->delete_cadetevent($eventID);
            redirect('cadetevent/index');
        }
        else
            show_error('The cadetevent you are trying to delete does not exist.');
    }
    
}
