<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadetevent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->library('session'); 
        
        if( $this->session->userdata('login') === true )
        {
            $this->load->model('Cadetevent_model');
        }
        else
        {
            redirect('login/view');
        }
    } 
    
    function view()
    {
        $data['title'] = 'Set Attendance';

        $this->load->model('Cadet_model');

        $data['event'] =  $this->Cadetevent_model->get_cadetevent( $this->input->post('event') );
        $data['cadets'] = $this->Cadet_model->get_all_cadets();

        // Loads the home page 
        $this->load->view('templates/header', $data);
        $this->load->view('pages/attend.php');
        $this->load->view('templates/footer');   
    }

    /*
     * Listing of cadetevent
     */
    function index()
    {
        $data['cadetevent'] = $this->Cadetevent_model->get_all_cadetevent();
        
        $data['_view'] = 'cadetevent/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cadetevent
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            if($this->input->post('type') === "pt")
            {
                $pt = 1;
                $llab = 0;
            }
            else if($this->input->post('type') === "llab")
            {
                $pt = 0;
                $llab = 1;
            }
            else
            {
                $pt = 0;
                $llab = 0;
            }
            $params = array(
				'name' => $this->input->post('name'),
				'date' => $this->input->post('date'),
				'pt' => $pt,
				'llab' => $llab,
            );
            
            $cadetevent_id = $this->Cadetevent_model->add_cadetevent($params);
            redirect('attendance/view');
        }
        else
        {            
            $data['_view'] = 'cadetevent/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cadetevent
     */
    function edit($eventID)
    {   
        // check if the cadetevent exists before trying to edit it
        $data['cadetevent'] = $this->Cadetevent_model->get_cadetevent($eventID);
        
        if(isset($data['cadetevent']['eventID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'date' => $this->input->post('date'),
					'pt' => $this->input->post('pt'),
					'llab' => $this->input->post('llab'),
                );

                $this->Cadetevent_model->update_cadetevent($eventID,$params);            
                redirect('cadetevent/index');
            }
            else
            {
                $data['_view'] = 'cadetevent/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cadetevent you are trying to edit does not exist.');
    } 

    /*
     * Deleting cadetevent
     */
    function remove()
    {
        $cadetevent = $this->Cadetevent_model->get_cadetevent($this->input->post('event'));

        // check if the cadetevent exists before trying to delete it
        if(isset($cadetevent['eventID']))
        {
            $this->Cadetevent_model->delete_cadetevent($this->input->post('event'));
            redirect('attendance/admin');
        }
        else
            show_error('The cadetevent you are trying to delete does not exist.');
    }
    
}
