<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadetgroup extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cadetgroup_model');
    } 

    /*
     * Listing of cadetgroup
     */
    function index()
    {
        $data['cadetgroup'] = $this->Cadetgroup_model->get_all_cadetgroup();
        
        $data['_view'] = 'cadetgroup/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new cadetgroup
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'label' => $this->input->post('label'),
            );
            
            $cadetgroup_id = $this->Cadetgroup_model->add_cadetgroup($params);
            redirect('cadetgroup/index');
        }
        else
        {            
            $data['_view'] = 'cadetgroup/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cadetgroup
     */
    function edit($id)
    {   
        // check if the cadetgroup exists before trying to edit it
        $data['cadetgroup'] = $this->Cadetgroup_model->get_cadetgroup($id);
        
        if(isset($data['cadetgroup']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'label' => $this->input->post('label'),
                );

                $this->Cadetgroup_model->update_cadetgroup($id,$params);            
                redirect('cadetgroup/index');
            }
            else
            {
                $data['_view'] = 'cadetgroup/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The cadetgroup you are trying to edit does not exist.');
    } 

    /*
     * Deleting cadetgroup
     */
    function remove($id)
    {
        $cadetgroup = $this->Cadetgroup_model->get_cadetgroup($id);

        // check if the cadetgroup exists before trying to delete it
        if(isset($cadetgroup['id']))
        {
            $this->Cadetgroup_model->delete_cadetgroup($id);
            redirect('cadetgroup/index');
        }
        else
            show_error('The cadetgroup you are trying to delete does not exist.');
    }
    
}
