<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Wiki extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('wiki_model');
    } 

    /*
     * Listing of wiki
     */
    function view()
    {
        $data['title'] = 'Detachment Wiki';
        $data['wikis'] = $this->wiki_model->get_all_wikis();

        $this->load->view('templates/header', $data);
        $this->load->view('pages/wikihome.php');
        $this->load->view('templates/footer'); 
    }

    /*
     * Adding a new wiki
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'body' => $this->input->post('body'),
            );
            
            $wiki_id = $this->Wiki_model->add_wiki($params);
            redirect('wiki/index');
        }
        else
        {            
            $data['_view'] = 'wiki/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a wiki
     */
    function edit()
    {       
        if( $this->input->post('wiki') !== null )
        {
            $data['title'] = 'Edit Detachment Wiki';
            
            $data['wiki'] = $this->wiki_model->get_wiki($this->input->post('wiki'));

            $this->load->view('templates/header', $data);
            $this->load->view('pages/editwiki.php');
            $this->load->view('templates/footer'); 
        }
        else
        {
            show_error('The wiki you are trying to edit does not exist.');
        }
    } 
    
    /*
     * Saves changes made to the wiki.
     */
    function save()
    {
        if( $this->input->post('modifiedwiki') !== null )
        {
            $params = array(
                'body' => $this->input->post('savewiki'),
            );
            
            $this->wiki_model->update_wiki($this->input->post('modifiedwiki'), $params);

            $data['wikis'] = $this->wiki_model->get_all_wikis();
            
            $this->load->view('templates/header', $data);
            $this->load->view('pages/wikihome.php');
            $this->load->view('templates/footer'); 
        }
        else
        {
            show_error('The wiki you are trying to edit does not exist.');
        }
    }

    /*
     * Deleting wiki
     */
    function remove($id)
    {
        $wiki = $this->Wiki_model->get_wiki($id);

        // check if the wiki exists before trying to delete it
        if(isset($wiki['id']))
        {
            $this->Wiki_model->delete_wiki($id);
            redirect('wiki/index');
        }
        else
            show_error('The wiki you are trying to delete does not exist.');
    }
    
}
