<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Wiki extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Wiki_model');
    } 

    /*
     * Listing of wiki
     */
    function index()
    {
        $data['wiki'] = $this->Wiki_model->get_all_wiki();
        
        $data['_view'] = 'wiki/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new wiki
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'body' => $this->input->post('body'),
            );
            
            $wiki_id = $this->Wiki_model->add_wiki($params);
            redirect('wiki/index');
        }
        else
        {            
            $data['_view'] = 'wiki/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a wiki
     */
    function edit($name)
    {   
        // check if the wiki exists before trying to edit it
        $data['wiki'] = $this->Wiki_model->get_wiki($name);
        
        if(isset($data['wiki']['name']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'body' => $this->input->post('body'),
                );

                $this->Wiki_model->update_wiki($name,$params);            
                redirect('wiki/index');
            }
            else
            {
                $data['_view'] = 'wiki/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The wiki you are trying to edit does not exist.');
    } 

    /*
     * Deleting wiki
     */
    function remove($name)
    {
        $wiki = $this->Wiki_model->get_wiki($name);

        // check if the wiki exists before trying to delete it
        if(isset($wiki['name']))
        {
            $this->Wiki_model->delete_wiki($name);
            redirect('wiki/index');
        }
        else
            show_error('The wiki you are trying to delete does not exist.');
    }
    
}
