<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadetgroup_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cadetgroup by id
     */
    function get_cadetgroup($id)
    {
        return $this->db->get_where('cadetGroup',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all cadetgroup
     */
    function get_all_cadetgroup()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('cadetGroup')->result_array();
    }
        
    /*
     * function to add new cadetgroup
     */
    function add_cadetgroup($params)
    {
        $this->db->insert('cadetGroup',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cadetgroup
     */
    function update_cadetgroup($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cadetGroup',$params);
    }
    
    /*
     * function to delete cadetgroup
     */
    function delete_cadetgroup($id)
    {
        return $this->db->delete('cadetGroup',array('id'=>$id));
    }
}
