<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadet_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cadet by rin
     */
    function get_cadet($rin)
    {
        return $this->db->get_where('cadet',array('rin'=>$rin))->row_array();
    }
        
    /*
     * Get all cadet
     */
    function get_all_cadet()
    {
        $this->db->order_by('rin', 'desc');
        return $this->db->get('cadet')->result_array();
    }
        
    /*
     * function to add new cadet
     */
    function add_cadet($params)
    {
        $this->db->insert('cadet',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cadet
     */
    function update_cadet($rin,$params)
    {
        $this->db->where('rin',$rin);
        return $this->db->update('cadet',$params);
    }
    
    /*
     * function to delete cadet
     */
    function delete_cadet($rin)
    {
        return $this->db->delete('cadet',array('rin'=>$rin));
    }
}
