<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cadetevent_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cadetevent by eventID
     */
    function get_cadetevent($eventID)
    {
        return $this->db->get_where('cadetEvent',array('eventID'=>$eventID))->row_array();
    }
    
    /*
     * Gets total of a given event.
     */
    function get_event_total($event)
    {
        $this->db->from('cadetEvent');
        $query = $this->db->where($event, 1);
        return $query->count_all_results();
    }
    
    /*
     * Gets 5 closest cadetevents by date
     */
    function get_last_five_events()
    {
        return $this->db->query('SELECT * FROM cadetEvent ORDER BY ABS( DATEDIFF( cadetEvent.date, NOW() ) ) LIMIT 5')->result_array();
    }
        
    /*
     * Get all cadetevent
     */
    function get_all_cadetevents()
    {
        return $this->db->query('SELECT * FROM cadetEvent ORDER BY ABS( DATEDIFF( cadetEvent.date, NOW() ) )')->result_array();
    }
        
    /*
     * function to add new cadetevent
     */
    function add_cadetevent($params)
    {
        $this->db->insert('cadetEvent',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cadetevent
     */
    function update_cadetevent($eventID,$params)
    {
        $this->db->where('eventID',$eventID);
        return $this->db->update('cadetEvent',$params);
    }
    
    /*
     * function to delete cadetevent
     */
    function delete_cadetevent($eventID)
    {
        return $this->db->delete('cadetEvent',array('eventID'=>$eventID));
    }
}
