<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupmember_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get groupmember by 
     */
    function get_groupmember($)
    {
        return $this->db->get_where('groupMember',array(''=>$))->row_array();
    }
        
    /*
     * Get all groupmember
     */
    function get_all_groupmember()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('groupMember')->result_array();
    }
        
    /*
     * function to add new groupmember
     */
    function add_groupmember($params)
    {
        $this->db->insert('groupMember',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update groupmember
     */
    function update_groupmember($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('groupMember',$params);
    }
    
    /*
     * function to delete groupmember
     */
    function delete_groupmember($)
    {
        return $this->db->delete('groupMember',array(''=>$));
    }
}
