<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupmember_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get groupmember by 
     */
    function get_groupmember( $rin )
    {
        return $this->db->get_where('groupMember',array('rin'=>$rin))->row_array();
    }
    
    /*
     * Returns true if cadet is in group and false otherwise.
     */
    function in_group( $label, $rin )
    {
        $this->db->join('cadetGroup', 'cadetGroup.id = groupMember.groupID');

        $this->db->where('rin', $rin);
        $this->db->where('label', $label);
        $query = $this->db->get('groupMember');
        
        if($query->num_rows() > 0)
        {
            return true;
        }
        else 
        {
            return false;
        }
    }

    /*
     * Checks to see if a user is an admin.
     */
    function is_admin($rin)
    {
        $this->db->where('rin', $rin);
        $this->db->where('label', 'admin');

        $this->db->join('cadetGroup', 'cadetGroup.id = groupMember.groupID');

        $query = $this->db->get('groupMember');

        if($query->num_rows() > 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
        
    /*
     * Get all groupmembers of a given group
     */
    function get_all_groupmembers( $id )
    {
        return $this->db->get_where('groupMember',array('groupID'=>$id))->result_array();
    }
        
    /*
     * function to add new groupmember
     */
    function add_groupmember($params)
    {
        $this->db->insert('groupMember',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update groupmember
     */
    function update_groupmember($id,$params)
    {
        $this->db->where('groupID',$id);
        return $this->db->update('groupMember',$params);
    }
    
    /*
     * function to delete groupmember
     */
    function delete_groupmember($rin, $id)
    {
        return $this->db->delete('groupMember',array('rin'=>$rin, 'groupID'=>$id));
    }
}
