<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Groupmember_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get groupmember by 
     */
    function get_groupmember( $rin )
    {
        return $this->db->get_where('groupMember',array('rin'=>$rin))->row_array();
    }
        
    /*
     * Get all groupmembers of a given group
     */
    function get_all_groupmembers( $id )
    {
        return $this->db->get_where('groupMember',array('groupID'=>$id))->result_array();
    }
        
    /*
     * function to add new groupmember
     */
    function add_groupmember($params)
    {
        $this->db->insert('groupMember',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update groupmember
     */
    function update_groupmember($id,$params)
    {
        $this->db->where('groupID',$id);
        return $this->db->update('groupMember',$params);
    }
    
    /*
     * function to delete groupmember
     */
    function delete_groupmember($rin, $id)
    {
        return $this->db->delete('groupMember',array('rin'=>$rin, 'groupID'=>$id));
    }
}
