<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Wiki_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get wiki by name
     */
    function get_wiki($id)
    {
        return $this->db->get_where('wiki',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all wiki
     */
    function get_all_wikis()
    {
        $this->db->order_by('name', 'asc');
        return $this->db->get('wiki')->result_array();
    }
        
    /*
     * function to add new wiki
     */
    function add_wiki($params)
    {
        $this->db->insert('wiki',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update wiki
     */
    function update_wiki($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('wiki',$params);
    }
    
    /*
     * function to delete wiki
     */
    function delete_wiki($id)
    {
        return $this->db->delete('wiki',array('id'=>$id));
    }
}
